# docker-compose.yml
version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
